name: First Workflow

on:
  push:
    branches: [main]
permissions:
  contents: write
 

jobs:

  first-job:

    runs-on: ubuntu-latest

    steps:

      - name: Welcome Message
        run: echo "Hello GitHub Actions"

      - name: Show Date
        run: date

      - name: List Files
        run: ls -la
      - name: Trigger Workflow B
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-second-workflow
          client-payload: '{"ref": "${{ github.ref }}"}'  
